/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recipe;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Double.parseDouble;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author mihailvd
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    ArrayList<Recipe> recipes = new ArrayList<>();
//    JList list;
    int[] selected;
//    File recipeFile = new File("recipes.txt");

    public main() {

        BufferedReader reader;
        LinkedList<String> items = new LinkedList<>();
        try {
            reader = new BufferedReader(new FileReader("recipes.txt"));
            String line = reader.readLine();

            while (line != null) {
                String[] sections = line.split("-");
                String name = sections[0];
                Double time = Double.valueOf(sections[1]);
                String[] ings = sections[2].split("\\+")[0].split(",");
                HashMap<String, String> ingrs = new HashMap<>();
                for (String ing : ings) {
                    String ing1 = ing.split(":")[0];
                    String quan = ing.split(":")[1];
                    ingrs.put(ing1, quan);
                }
                LinkedList<String> stps = new LinkedList<>();
                String[] steps = sections[2].split("\\+")[1].split(",");
                for (String step : steps) {
                    stps.add(step);
                }
                Recipe rsp = new Recipe(name, time, ingrs, stps);
                this.recipes.add(rsp);
                System.out.println(rsp.toString());
                items.add(name);
                line = reader.readLine();
            }

            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        String[] names = new String[items.size()];

        for (int i = 0; i < items.size(); i++) {
            names[i] = items.get(i);
        }

        myInitComponents(names);
        initComponents();

    }

    public main(ArrayList<Recipe> rps) {
        this.recipes = rps;
        String[] names = new String[rps.size()];
        for (int i = 0; i < rps.size(); i++) {
            names[i] = rps.get(i).getName();
        }
        myInitComponents(names);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
//    private String getSelectionIndex() {
//        return String.valueOf(list.getSelectedIndex());
//    }
    public void myInitComponents(String[] names) {
        JList list = new JList(names);
        list.setBackground(new Color(207, 160, 90));
        list.setPreferredSize(new Dimension(480, 650));

        list.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                System.out.println(list.getSelectedIndices()[0]);
                selected = list.getSelectedIndices();
//                System.out.println(list.getSelectedIndex());
            }
        });
        setLayout(new FlowLayout());

        add(list);

        pack();

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SearchName = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        SearchIng = new javax.swing.JTextField();
        addButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 160, 90));

        jPanel4.setBackground(new java.awt.Color(159, 89, 34));
        jPanel4.setForeground(new java.awt.Color(127, 61, 8));

        addButton.setBackground(new java.awt.Color(220, 177, 129));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton.setText("Search");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(220, 177, 129));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Delete");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SearchName.setText("Search");
        SearchName.setToolTipText("Search name");
        SearchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchNameMouseClicked(evt);
            }
        });
        SearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchNameActionPerformed(evt);
            }
        });

        addButton1.setBackground(new java.awt.Color(220, 177, 129));
        addButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton1.setText("Add");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        SearchIng.setText("Search ingredients");
        SearchIng.setToolTipText("Search ingredients");
        SearchIng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchIngMouseClicked(evt);
            }
        });

        addButton2.setBackground(new java.awt.Color(220, 177, 129));
        addButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton2.setText("Search");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchIng, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchName)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(addButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SearchIng, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(237, 203, 164));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String name = SearchName.getText();
        ArrayList<Recipe> recipes2 = new ArrayList<>();
        for (Recipe recipe : this.recipes) {
            String recipeName = recipe.getName().toLowerCase();
            System.out.println(recipeName);
            System.out.println(name);
            if (recipeName.startsWith(name.toLowerCase())) {
                recipes2.add(recipe);
            }
        }
        main obj = new main(recipes2);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void SearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchNameActionPerformed
        // TODO add your handling code here:
        SearchName.setText("");
    }//GEN-LAST:event_SearchNameActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:

//                    JPanel recipePanel = new JPanel();
//                    recipePanel.setLayout(new FlowLayout());
//                    JLabel label = new JLabel("hfueiw");
//                    recipePanel.setBackground(Color.BLUE);
//                    recipePanel.add(label);
        AddFrame obj = new AddFrame();
        obj.setVisible(true);

        dispose();
    }//GEN-LAST:event_addButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Recipe> newRsp = new ArrayList<>();
        for (int i = 0; i < this.recipes.size(); i++) {
            boolean write = true;
            for (int j = 0; j < selected.length; j++) {
                if (i == selected[j]) {
                    //zapisvame v fail
                    write = false;
                    break;
                }
            }
            if (write) {
                newRsp.add(this.recipes.get(i));
            }
        }
     FileWriter recipeWriter;
        this.recipes = newRsp;
            String txt="";
       try {
           for(Recipe recipe: this.recipes) {
               txt+=recipe.toString();
           }
                recipeWriter = new FileWriter("recipes.txt");
                recipeWriter.write(txt);
                recipeWriter.close();
            } catch (IOException ex) {
              //  Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        

     
        // Get all the selected items using the indices
        main obj = new main(this.recipes);
        obj.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
        String ing = SearchIng.getText();
        System.out.println(ing);
        ArrayList<Recipe> recipes2 = new ArrayList<>();
        for (Recipe recipe : this.recipes) {
            HashMap<String, String> recipeIng = recipe.getIngredients();
            System.out.println(recipeIng);
            if (recipeIng.containsKey(ing)) {
                recipes2.add(recipe);
            }
        }
        this.recipes = recipes2;
        main obj = new main(recipes);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_addButton2ActionPerformed

    private void SearchIngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchIngMouseClicked
        // TODO add your handling code here:
        SearchIng.setText("");
    }//GEN-LAST:event_SearchIngMouseClicked

    private void SearchNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchNameMouseClicked
        // TODO add your handling code here:
        SearchName.setText("");
    }//GEN-LAST:event_SearchNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ArrayList<Recipe> recipes = new ArrayList<>();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchIng;
    private javax.swing.JTextField SearchName;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
